[package]
name = "RustLuac"
version = "0.1.0"
authors = ["sohardforaname <organic_chemistry@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ll_syntax_proofer = { path = "./ll_syntax_proofer" }
